version: '3'

services:

  elastic_search: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: jaeger_elastic
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - test_net
    command: ["elasticsearch", "-Elogger.level=WARN"]

  agent: 
    image: jaegertracing/jaeger-agent
    container_name: jaeger_agent
    environment:
      REPORTER_GRPC_HOST_PORT=collector:14250
    networks:
      - test_net

  collector:
    image: jaegertracing/jaeger-collector
    container_name: jaeger_collector
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elastic_search:9200
      - LOG_LEVEL=warn
    networks:
      - test_net

  query:
    image: jaegertracing/jaeger-query:latest
    container_name: jaeger_query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elastic_search:9200
      - JAEGER_AGENT_HOST=agent
      - JAEGER_AGENT_PORT=6831
      - LOG_LEVEL=warn                
    networks:
      - test_net

  nginx:
    build:
      context: ./nginx
    image: jaeger_nginx
    container_name: jaeger_nginx
    ports:
      - "8080:80"
    networks:
      - test_net
    healthcheck:
        test: ["CMD", "curl", "-f", "http://query:16686"]
        interval: 30s
        timeout: 10s
        retries: 5    

volumes:
  elastic_data:

networks:
  test_net:
    driver: overlay
