version: '3'

services:

  elastic_search: &param
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: jaeger_cassandra
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - test_net

  agent:
    image: jaegertracing/jaeger-agent
    container_name: jaeger_agent
    #environment:
      #- REPORTER_GRPC_HOST_PORT=collector:14250
    depends_on:
      - collector
    <<: *param

  collector:
    image: jaegertracing/jaeger-collector
    container_name: jaeger_collector
    environment: #&envs
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elastic_search:9200
      - LOG_LEVEL=warn
    depends_on:
      - elastic_search
    <<: *param

  query:
    image: jaegertracing/jaeger-query:latest
    container_name: jaeger_query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elastic_search:9200
      - JAEGER_AGENT_HOST=agent
      - JAEGER_AGENT_PORT=6831
      - LOG_LEVEL=warn                
    depends_on:
      - elastic_search
    <<: *param

  nginx:
    build:
      context: ./nginx
    image: jaeger_nginx
    container_name: jaeger_nginx
    ports:
    - "8080:80"
    depends_on:
      - query
    <<: *param

volumes:
  elastic_data:

networks:
  test_net:
    driver: overlay
