version: '3.4'

x-template: &templ
  networks:
    - test_net
  deploy:
    mode: replicated
    replicas: 1
    placement:
      constraints: [node.role == worker]

volumes:
  elastic_data:

networks:
  test_net:
    driver: overlay

      
services:        
  elastic_search: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.elasticsearch == test]
    networks:
      - test_net

  agent: 
    image: jaegertracing/jaeger-agent
    environment:
      - REPORTER_GRPC_HOST_PORT=collector:14250
      - LOG_LEVEL=warn
    <<: *templ

  collector:
    image: jaegertracing/jaeger-collector
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elastic_search:9200
      - LOG_LEVEL=warn
    <<: *templ

  query:
    image: jaegertracing/jaeger-query:latest
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elastic_search:9200
      - JAEGER_AGENT_HOST=agent
      - JAEGER_AGENT_PORT=6831
      - LOG_LEVEL=warn                
    <<: *templ

  nginx:
    build:
      context: ./nginx
    image: jaeger_nginx
    ports:
      - "80:80"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://query:16686"]
        interval: 30s
        timeout: 10s
        retries: 5
    <<: *templ  